routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AirportController;
use App\Http\Controllers\RouteController;
use App\Http\Controllers\AirlineController;
use App\Http\Controllers\AirplaneSeatController;
use App\Http\Controllers\PlaneController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/', [LoginController::class, 'authenticate'])->name('login.authenticate')->middleware('guest');
Route::post('/logout', [LoginController::class, 'logout']);

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.','middleware' => 'auth'], function () {

    Route::get('/', [DashboardController::class, 'index']);

    // airport
    Route::resource('airport', AirportController::class);
    Route::get('/print/airport', [AirportController::class, 'print'])->name('print.airport');
    Route::get('/trash/airport', [AirportController::class, 'show_restore'])->name('trash.airport');
    Route::get('/trash/airport/{id}', [AirportController::class, 'restore'])->name('restore.airport');
    Route::get('/trash/airport/delete/{id}', [AirportController::class, 'delete'])->name('delete.airport');

    // route
    Route::resource('route', RouteController::class);
    Route::get('/print/route', [RouteController::class, 'print'])->name('print.route');
    Route::get('/trash/route', [RouteController::class, 'show_restore'])->name('trash.route');
    Route::get('/trash/route/restore/{id}', [RouteController::class, 'restore'])->name('restore.route');
    Route::get('/trash/route/delete/{id}', [RouteController::class, 'delete'])->name('delete.route');

    // airline
    Route::resource('airline', AirlineController::class);
    Route::get('/print/airline', [AirlineController::class, 'print'])->name('print.airline');
    Route::get('/trash/airline', [AirlineController::class, 'show_restore'])->name('trash.airline');
    Route::get('/trash/airline/restore/{id}', [AirlineController::class, 'restore'])->name('restore.airline');
    Route::get('/trash/airline/delete/{id}', [AirlineController::class, 'delete'])->name('delete.airline');

    // plane
    Route::resource('plane', PlaneController::class);
    Route::get('/print/plane', [PlaneController::class, 'print'])->name('print.plane');
    Route::get('/print/detail-plane/{plane}', [PlaneController::class, 'print_detail'])->name('print_detail.plane');
    Route::get('/trash/plane', [PlaneController::class, 'show_restore'])->name('trash.plane');
    Route::get('/trash/plane/restore/{id}', [PlaneController::class, 'restore'])->name('restore.plane');
    Route::get('/trash/plane/delete/{id}', [PlaneController::class, 'delete'])->name('delete.plane');

    // schedule
    Route::resource('schedule', ScheduleController::class);
    Route::get('/print/schedule', [ScheduleController::class, 'print'])->name('print.schedule');
    Route::get('/trash/schedule', [ScheduleController::class, 'show_restore'])->name('trash.schedule');
    Route::get('/trash/schedule/restore/{id}', [ScheduleController::class, 'restore'])->name('restore.schedule');
    Route::get('/trash/schedule/delete/{id}', [ScheduleController::class, 'delete'])->name('delete.schedule');

    // airplane seat
    Route::resource('airplane_seat', AirplaneSeatController::class);
    Route::get('/print/airplane_seat', [AirplaneSeatController::class, 'print'])->name('print.airplane_seat');
    Route::get('/trash/airplane_seat', [AirplaneSeatController::class, 'show_restore'])->name('trash.airplane_seat');
    Route::get('/trash/airplane_seat/restore/{id}', [AirplaneSeatController::class, 'restore'])->name('restore.airplane_seat');
    Route::get('/trash/airplane_seat/delete/{id}', [AirplaneSeatController::class, 'delete'])->name('delete.airplane_seat');

    // customer
    Route::resource('customer', CustomerController::class);
    Route::get('/print/customer', [CustomerController::class, 'print'])->name('print.customer');
    Route::get('/print/detail-customer/{customer}', [CustomerController::class, 'print_detail'])->name('print_detail.customer');
    Route::get('/trash/customer', [CustomerController::class, 'show_restore'])->name('trash.customer');
    Route::get('/trash/customer/restore/{id}', [CustomerController::class, 'restore'])->name('restore.customer');
    Route::get('/trash/customer/delete/{id}', [CustomerController::class, 'delete'])->name('delete.customer');


    // ticket
    Route::resource('ticket', TicketController::class);
    Route::get('/print/ticket', [TicketController::class, 'print'])->name('print.ticket');
    Route::get('/print/detail-ticket/{ticket}', [TicketController::class, 'print_detail'])->name('print_detail.ticket');
    Route::get('/trash/ticket', [TicketController::class, 'show_restore'])->name('trash.ticket');
    Route::get('/trash/ticket/restore/{id}', [TicketController::class, 'restore'])->name('restore.ticket');
    Route::get('/trash/ticket/delete/{id}', [TicketController::class, 'delete'])->name('delete.ticket');
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.','middleware' => 'superadmin'], function () {
    

    Route::resource('user', UserController::class);
    Route::get('/print/user', [UserController::class, 'print'])->name('print.user');
    Route::get('/trash/user', [UserController::class, 'show_restore'])->name('trash.user');
    Route::get('/trash/user/restore/{id}', [UserController::class, 'restore'])->name('restore.user');
    Route::get('/trash/user/delete/{id}', [UserController::class, 'delete'])->name('delete.user');
});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Airline;
use App\Models\Airport;
use App\Models\Customer;
use App\Models\Plane;
use App\Models\Route;
use App\Models\User;
use App\Models\Ticket;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    
    public function index()
    {
        $airport = Airport::count();
        $route = Route::count();
        $airline = Airline::count();
        $plane = Plane::count();
        $customer = Customer::count();
        $admin = User::where('role', '=', 'admin')->count();
        $ticket = Ticket::where('status', '=', 'Belum Terpakai')->count();

        return view('pages.dashboard', compact('airport', 'route', 'airline', 'plane', 'customer', 'admin', 'ticket'));
    }
}

resources/views/pages/dashboard/admin/create.blade.php
@extends('layouts.app')

@section('title')
Tambah User | {{ config('app.name') }}
@endsection

@section('content')
<div class="section-header">
  <h1>Tambah Data User</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item"><a href="#">Dashboard</a></div>
    <div class="breadcrumb-item"><a href="#">Data User</a></div>
    <div class="breadcrumb-item active">Tambah Data</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form action="{{ route('dashboard.user.store') }}" method="POST">
            @csrf
            <div class="form-group">
              <label for="name">Nama</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" required>
              @error('name')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
              @error('email')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" id="password" name="password" value="{{ old('password') }}"
                required>
              @error('password')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="role">Role</label>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="role" id="admin" value="admin" {{
                  old('role')=='Admin' ? 'checked' : '' }}>
                <label class="form-check-label" for="admin">
                  Admin
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="role" id="user" value="user" {{ old('role')=='User'
                  ? 'checked' : '' }}>
                <label class="form-check-label" for="user">
                  User
                </label>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-page')
<script>
  function previewImage() {
      const logo = document.querySelector('#logo');
      const imgPreview = document.querySelector('.img-preview');
      const blob = URL.createObjectURL(logo.files[0]);
      imgPreview.src = blob;
    }
</script>
@endpush

resources/views/pages/dashboard/admin/edit.blade.php
@extends('layouts.app')

@section('title')
Edit User | {{ config('app.name') }}
@endsection

@section('content')
<div class="section-header">
  <h1>Edit Data User</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item"><a href="#">Dashboard</a></div>
    <div class="breadcrumb-item"><a href="#">Data User</a></div>
    <div class="breadcrumb-item active">Edit Data</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form action="{{ route('dashboard.user.update', $user->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
              <label for="name">Nama</label>
              <input type="text" class="form-control" id="name" name="name" value="{{ old('name', $user->name) }}"
                required>
              @error('name')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="text" class="form-control" id="email" name="email" value="{{ old('email', $user->email) }}"
                required>
              @error('email')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="password">Password</label>
              <input type="password" class="form-control" id="password" name="password" value="{{ old('password') }}">
              @error('password')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="role">Role</label>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="role" id="admin" value="admin" {{ old('role',
                  $user->role)=='admin' ? 'checked' : '' }}>
                <label class="form-check-label" for="admin">
                  Admin
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="role" id="user" value="user" {{ old('role',
                  $user->role)=='user'
                ? 'checked' : '' }}>
                <label class="form-check-label" for="user">
                  User
                </label>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Ubah</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-page')
<script>
  function previewImage() {
      const logo = document.querySelector('#logo');
      const imgPreview = document.querySelector('.img-preview');
      const blob = URL.createObjectURL(logo.files[0]);
      imgPreview.src = blob;
    }
</script>
@endpush

resources/views/pages/dashboard/admin/index.blade.php
@extends('layouts.app')

@section('title')
Data User | {{ config('app.name') }}
@endsection

@push('css-libraries')
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-bs4/css/dataTables.bootstrap4.min.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-select-bs4/css/select.bootstrap4.min.css") }}>
@endpush

@section('content')
<div class="section-header">
  <h1>Data User</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('dashboard.') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Data User</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body d-flex justify-content-between">
          <a href="{{ route('dashboard.user.create') }}" class="btn btn-primary"><i class="fas fa-plus"
              aria-hidden="true"></i> Tambah Data</a>
          <a href="{{ route('dashboard.print.user') }}" class=" btn btn-dark"><i class="fas fa-file-pdf"
              aria-hidden="true"></i> Cetak PDF</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped" id="table-1">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($users as $user)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $user->name }}</td>
                  <td>{{ $user->email }}</td>
                  <td>{{ $user->role }}</td>
                  <td>
                    <a href="{{ route('dashboard.user.edit', $user->id) }}" class="btn btn-warning"><i class="fa fa-pen"
                        aria-hidden="true"></i></a>
                    <form action="{{ route('dashboard.user.destroy', $user->id) }}" method="POST" class="d-inline">
                      @csrf
                      @method('delete')
                      <button class="btn btn-danger btn-delete" data-toggle="tooltip" title='Delete'><i
                          class="fas fa-trash" aria-hidden="true"></i></button>
                    </form>
                  </td>
                </tr>
                @empty
                <tr>
                  <td colspan="5" class="text-center">Tidak ada data</td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-libraries')
<script src={{ asset("assets/module/datatables/media/js/jquery.dataTables.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-bs4/js/dataTables.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-select-bs4/js/select.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/sweetalert/dist/sweetalert.min.js") }}></script>
@endpush

@push('js-page')
<script src={{ asset("assets/js/page/modules-datatables.js") }}></script>
@endpush

@push('alert-js')
<script>
  $(".btn-delete").click(function(e) {
    var form = $(this).closest("form");
    var name = $(this).data("name");
    e.preventDefault();
    swal({
      title: 'Yakin ingin menghapus data?',
      text: 'Data akan masuk ke dalam menu trash',
      icon: 'warning',
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        form.submit();
      } else {
        swal('Proses Hapus dibatalkan');
      }
    });
  });
</script>
@endpush

resources/views/pages/dashboard/admin/print.blade.php
@extends('layouts.app-print')

@section('content')
<div class="">
  <h3 class="text-center my-5">Laporan Data User</h3>
  <table class="table table-bordered ">
    <thead class="thead-light">
      <tr class="text-center">
        <th>No</th>
        <th>Nama</th>
        <th>Email</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($users as $user)
      <tr class="text-center">
        <td>{{ $loop->iteration }}</td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td>{{ $user->role }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="4" class="text-center">Tidak ada data</td>
      </tr>
      @endforelse
    </tbody>
  </table>
</div>
@endsection

resources/views/pages/dashboard/admin/trash.blade.php
@extends('layouts.app')

@section('title')
Trashed Data User | {{ config('app.name') }}
@endsection

@push('css-libraries')
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-bs4/css/dataTables.bootstrap4.min.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-select-bs4/css/select.bootstrap4.min.css") }}>
@endpush

@section('content')
<div class="section-header">
  <h1>Data User</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('dashboard.') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Trashed Data User</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped" id="table-1">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($users as $user)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $user->name }}</td>
                  <td>{{ $user->email }}</td>
                  <td>{{ $user->role }}</td>
                  <td>
                    <a href="{{ route('dashboard.restore.user', $user->id) }}" class="btn btn-success btn-restore"><i
                        class="fa fa-trash-restore" aria-hidden="true"></i></a>
                    <a href="{{ route('dashboard.delete.user', $user->id) }}" class="btn btn-danger btn-delete"><i
                        class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
                @empty
                <tr>
                  <td colspan="5" class="text-center">Tidak ada data</td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-libraries')
<script src={{ asset("assets/module/datatables/media/js/jquery.dataTables.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-bs4/js/dataTables.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-select-bs4/js/select.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/sweetalert/dist/sweetalert.min.js") }}></script>
@endpush

@push('js-page')
<script src={{ asset("assets/js/page/modules-datatables.js") }}></script>
@endpush

@push('alert-js')
<script>
  $('.btn-restore').on('click', function (e) {
    e.preventDefault();
    const url = $(this).attr('href');
    swal({
      title: 'Are you sure?',
      text: 'Data akan kembali ke daftar user',
      icon: 'warning',
      buttons: ["Cancel", "Yes!"],
    }).then(function(value) {
      if (value) {
        window.location.href = url;
      }
    });
  });
  $('.btn-delete').on('click', function (e) {
    e.preventDefault();
    const url = $(this).attr('href');
    swal({
      title: 'Are you sure?',
      text: 'Data akan dihapus permanen',
      icon: 'warning',
      buttons: ["Cancel", "Yes!"],
    }).then(function(value) {
      if (value) {
        window.location.href = url;
      }
    });
  });
</script>
@endpush