routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AirportController;
use App\Http\Controllers\RouteController;
use App\Http\Controllers\AirlineController;
use App\Http\Controllers\AirplaneSeatController;
use App\Http\Controllers\PlaneController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/', [LoginController::class, 'authenticate'])->name('login.authenticate')->middleware('guest');
Route::post('/logout', [LoginController::class, 'logout']);

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.','middleware' => 'auth'], function () {

    Route::get('/', [DashboardController::class, 'index']);

    // airport
    Route::resource('airport', AirportController::class);
    Route::get('/print/airport', [AirportController::class, 'print'])->name('print.airport');
    Route::get('/trash/airport', [AirportController::class, 'show_restore'])->name('trash.airport');
    Route::get('/trash/airport/{id}', [AirportController::class, 'restore'])->name('restore.airport');
    Route::get('/trash/airport/delete/{id}', [AirportController::class, 'delete'])->name('delete.airport');

    // route
    Route::resource('route', RouteController::class);
    Route::get('/print/route', [RouteController::class, 'print'])->name('print.route');
    Route::get('/trash/route', [RouteController::class, 'show_restore'])->name('trash.route');
    Route::get('/trash/route/restore/{id}', [RouteController::class, 'restore'])->name('restore.route');
    Route::get('/trash/route/delete/{id}', [RouteController::class, 'delete'])->name('delete.route');

    // airline
    Route::resource('airline', AirlineController::class);
    Route::get('/print/airline', [AirlineController::class, 'print'])->name('print.airline');
    Route::get('/trash/airline', [AirlineController::class, 'show_restore'])->name('trash.airline');
    Route::get('/trash/airline/restore/{id}', [AirlineController::class, 'restore'])->name('restore.airline');
    Route::get('/trash/airline/delete/{id}', [AirlineController::class, 'delete'])->name('delete.airline');

    // plane
    Route::resource('plane', PlaneController::class);
    Route::get('/print/plane', [PlaneController::class, 'print'])->name('print.plane');
    Route::get('/print/detail-plane/{plane}', [PlaneController::class, 'print_detail'])->name('print_detail.plane');
    Route::get('/trash/plane', [PlaneController::class, 'show_restore'])->name('trash.plane');
    Route::get('/trash/plane/restore/{id}', [PlaneController::class, 'restore'])->name('restore.plane');
    Route::get('/trash/plane/delete/{id}', [PlaneController::class, 'delete'])->name('delete.plane');

    // schedule
    Route::resource('schedule', ScheduleController::class);
    Route::get('/print/schedule', [ScheduleController::class, 'print'])->name('print.schedule');
    Route::get('/trash/schedule', [ScheduleController::class, 'show_restore'])->name('trash.schedule');
    Route::get('/trash/schedule/restore/{id}', [ScheduleController::class, 'restore'])->name('restore.schedule');
    Route::get('/trash/schedule/delete/{id}', [ScheduleController::class, 'delete'])->name('delete.schedule');

    // airplane seat
    Route::resource('airplane_seat', AirplaneSeatController::class);
    Route::get('/print/airplane_seat', [AirplaneSeatController::class, 'print'])->name('print.airplane_seat');
    Route::get('/trash/airplane_seat', [AirplaneSeatController::class, 'show_restore'])->name('trash.airplane_seat');
    Route::get('/trash/airplane_seat/restore/{id}', [AirplaneSeatController::class, 'restore'])->name('restore.airplane_seat');
    Route::get('/trash/airplane_seat/delete/{id}', [AirplaneSeatController::class, 'delete'])->name('delete.airplane_seat');

    // customer
    Route::resource('customer', CustomerController::class);
    Route::get('/print/customer', [CustomerController::class, 'print'])->name('print.customer');
    Route::get('/print/detail-customer/{customer}', [CustomerController::class, 'print_detail'])->name('print_detail.customer');
    Route::get('/trash/customer', [CustomerController::class, 'show_restore'])->name('trash.customer');
    Route::get('/trash/customer/restore/{id}', [CustomerController::class, 'restore'])->name('restore.customer');
    Route::get('/trash/customer/delete/{id}', [CustomerController::class, 'delete'])->name('delete.customer');


    // ticket
    Route::resource('ticket', TicketController::class);
    Route::get('/print/ticket', [TicketController::class, 'print'])->name('print.ticket');
    Route::get('/print/detail-ticket/{ticket}', [TicketController::class, 'print_detail'])->name('print_detail.ticket');
    Route::get('/trash/ticket', [TicketController::class, 'show_restore'])->name('trash.ticket');
    Route::get('/trash/ticket/restore/{id}', [TicketController::class, 'restore'])->name('restore.ticket');
    Route::get('/trash/ticket/delete/{id}', [TicketController::class, 'delete'])->name('delete.ticket');
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.','middleware' => 'superadmin'], function () {
    

    Route::resource('user', UserController::class);
    Route::get('/print/user', [UserController::class, 'print'])->name('print.user');
    Route::get('/trash/user', [UserController::class, 'show_restore'])->name('trash.user');
    Route::get('/trash/user/restore/{id}', [UserController::class, 'restore'])->name('restore.user');
    Route::get('/trash/user/delete/{id}', [UserController::class, 'delete'])->name('delete.user');
});

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ticket extends Model
{
    use HasFactory;
    use SoftDeletes;

    public $table = 'tickets';
    protected $guarded = ['id'];

    public static function boot()
    {
        parent::boot();


        self::creating(function ($model) {
            $date = date('Y');
            $rand = rand(0000, 9999);
            $customer_id = request()->customer_id;

            $kode = '#'. $date . $rand . $customer_id;
            $model->kode_tiket = $kode;
        });
    }

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function schedule()
    {
        return $this->belongsTo(Schedule::class);
    }

    public function airplaneSeat()
    {
        return $this->belongsTo(AirplaneSeat::class);
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\Airline;
use App\Models\Airport;
use App\Models\Customer;
use App\Models\Plane;
use App\Models\Route;
use App\Models\User;
use App\Models\Ticket;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    
    public function index()
    {
        $airport = Airport::count();
        $route = Route::count();
        $airline = Airline::count();
        $plane = Plane::count();
        $customer = Customer::count();
        $admin = User::where('role', '=', 'admin')->count();
        $ticket = Ticket::where('status', '=', 'Belum Terpakai')->count();

        return view('pages.dashboard', compact('airport', 'route', 'airline', 'plane', 'customer', 'admin', 'ticket'));
    }
}

app/Http/Controllers/TicketController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TicketRequest;
use App\Models\AirplaneSeat;
use App\Models\Customer;
use App\Models\Schedule;
use App\Models\Ticket;
use PDF;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Illuminate\Http\Request;

class TicketController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = Ticket::all();
        return view('pages.dashboard.ticket.index', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::all();
        $schedules = Schedule::all();
        $airplane_seats = AirplaneSeat::all(); 

        return view('pages.dashboard.ticket.create', compact('customers', 'schedules', 'airplane_seats'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TicketRequest $request)
    {
        $data = $request->all();

        $this->validate($request, [
            'customer_id' => 'required|unique:tickets',
        ]);

        Ticket::create($data);

        return redirect()->route('dashboard.ticket.index')->with('success', 'Data Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        $qrcode = QrCode::size(200)->generate($ticket->kode_tiket);
        return view('pages.dashboard.ticket.show', compact('ticket', 'qrcode'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        $customers = Customer::all();
        $schedules = Schedule::all();
        $airplane_seats = AirplaneSeat::all();

        return view('pages.dashboard.ticket.edit', compact('ticket', 'customers', 'schedules', 'airplane_seats'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TicketRequest $request, Ticket $ticket)
    {
        $data = $request->all();

        if($request->customer_id != $ticket->customer_id)  {
            $this->validate($request, [
                'customer_id' => 'required|unique:tickets',
            ]);
        }

        $ticket->update($data);

        return redirect()->route('dashboard.ticket.index')->with('success', 'Data Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        $ticket->delete();

        return redirect()->route('dashboard.ticket.index')->with('success', 'Data Berhasil Dihapus');
    }

    public function show_restore()
    {
        $tickets = Ticket::onlyTrashed()->get();
        return view('pages.dashboard.ticket.trash', compact('tickets'));
    }

    public function restore($id)
    {   
        $ticket = Ticket::onlyTrashed()->where('id',$id);
        $ticket->restore();
        return redirect()->route('dashboard.trash.ticket')->with('success', 'Data Berhasil Dikembalikan');
    }

    public function delete($id)
    {   
        $ticket = Ticket::onlyTrashed()->where('id',$id)->first();
        $ticket->forceDelete();
        return redirect()->route('dashboard.trash.ticket')->with('success', 'Data Berhasil Dihapus Permanen');
    }

    public function print()
    {
        $tickets = Ticket::all();
        $pdf = PDF::loadview('pages.dashboard.ticket.print', compact('tickets'));
    	return $pdf->download('laporan-data-ticket.pdf');
    }

    public function print_detail(Ticket $ticket)
    {
        $qrcode = base64_encode(QrCode::format('svg')->size(150)->generate($ticket->kode_tiket));
        $nama_file = 'data-detail-ticket-'.$ticket->kode_tiket.'.pdf';
        $pdf = PDF::loadview('pages.dashboard.ticket.print-detail', compact('ticket', 'qrcode'));
    	return $pdf->download($nama_file);
    }
}

resources/views/pages/dashboard/ticket/create.blade.php
@extends('layouts.app')

@section('title')
Tambah Tiket | {{ config('app.name') }}
@endsection

@push('css-libraries')
<link rel="stylesheet" href={{ asset("assets/module/select2/dist/css/select2.min.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/bootstrap-daterangepicker/daterangepicker.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/selectric/public/selectric.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/bootstrap-timepicker/css/bootstrap-timepicker.min.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/bootstrap-tagsinput/dist/bootstrap-tagsinput.css") }}>
@endpush

@section('content')
<div class="section-header">
  <h1>Tambah Data Tiket</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item"><a href="#">Dashboard</a></div>
    <div class="breadcrumb-item"><a href="#">Data Tiket</a></div>
    <div class="breadcrumb-item active">Tambah Data</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form action="{{ route('dashboard.ticket.store') }}" method="POST">
            @csrf
            <div class="form-group">
              <label for="customer_id">Nama</label>
              <select name="customer_id" required class="form-control select2">
                @foreach($customers as $customer)
                <option value="{{ $customer->id }}" {{ old('customer_id')==$customer->id ? 'selected' : '' }}>
                  {{ $customer->nama }}
                </option>
                @endforeach
              </select>
              @error('customer_id')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="schedule_id">Jadwal terbang</label>
              <select name="schedule_id" required class="form-control select2">
                @foreach($schedules as $schedule)
                <option value="{{ $schedule->id }}" {{ old('schedule_id')==$schedule->id ? 'selected' : '' }}>
                  {{ $schedule->plane->airline->nama ?? ''}} - {{ $schedule->plane->nama ?? ''}} - {{
                  $schedule->waktu_berangkat }} - {{ $schedule->waktu_tiba }}
                </option>
                @endforeach
              </select>
              @error('schedule_id')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="airplane_seat_id">Kursi</label>
              <select name="airplane_seat_id" required class="form-control select2">
                @foreach($airplane_seats as $airplane_seat)
                <option value="{{ $airplane_seat->id }}" {{ old('airplane_seat_id')==$airplane_seat->id ? 'selected' :
                  '' }}>
                  {{ $airplane_seat->plane->airline->nama ?? ''}} - {{ $airplane_seat->plane->nama ?? ''}} - {{
                  $airplane_seat->kelas_kursi }}
                </option>
                @endforeach
              </select>
              @error('airplane_seat_id')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="tanggal_pesan">Tanggal Pesan</label>
              <input type="text" class="form-control datepicker" id="tanggal_pesan" name="tanggal_pesan" required
                value="{{ old('tanggal_pesan') }}">
              @error('tanggal_pesan')
              <p class="text-danger">
                {{ $message }}
              </p>
              @enderror
            </div>
            <div class="form-group">
              <label for="status">Status</label>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="status" id="status" value="Belum Terpakai" {{
                  old('status')=='Belum Terpakai' ? 'checked' : '' }}>
                <label class="form-check-label" for="status">
                  Belum Terpakai
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="status" id="status1" value="Terpakai" {{
                  old('status')=='Terpakai' ? 'checked' : '' }}>
                <label class="form-check-label" for="status1">
                  Terpakai
                </label>
              </div>
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-libraries')
<script src={{ asset("assets/module/cleave.js/dist/cleave.min.js") }}></script>
<script src={{ asset("assets/module/select2/dist/js/select2.full.min.js") }}></script>
<script src={{ asset("assets/module/selectric/public/jquery.selectric.min.js") }}></script>
<script src={{ asset("assets/module/bootstrap-daterangepicker/daterangepicker.js") }}></script>
<script src={{ asset("assets/module/bootstrap-timepicker/js/bootstrap-timepicker.min.js") }}></script>
<script src={{ asset("assets/module/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js") }}></script>
@endpush

@push('js-page')
<script src={{ asset("assets/js/page/forms-advanced-forms.js") }}></script>
@endpush

resources/views/pages/dashboard/ticket/index.blade.php
@extends('layouts.app')

@section('title')
Data Tiket | {{ config('app.name') }}
@endsection

@push('css-libraries')
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-bs4/css/dataTables.bootstrap4.min.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-select-bs4/css/select.bootstrap4.min.css") }}>
@endpush

@section('content')
<div class="section-header">
  <h1>Data Tiket</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('dashboard.') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Data Tiket</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body d-flex justify-content-between">
          <a href="{{ route('dashboard.ticket.create') }}" class="btn btn-primary"><i class="fas fa-plus"
              aria-hidden="true"></i> Tambah Data</a>
          <a href="{{ route('dashboard.print.ticket') }}" class="btn btn-dark"><i class="fas fa-file-pdf"
              aria-hidden="true"></i> Cetak PDF</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped" id="table-1">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Pesawat</th>
                  <th>Tanggal Pesan</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($tickets as $ticket)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $ticket->customer->nama ?? '' }}</td>
                  <td>{{ $ticket->schedule->plane->nama ?? '' }}</td>
                  <td>{{ $ticket->tanggal_pesan }}</td>
                  <td>{{ $ticket->status }}</td>
                  <td>
                    <a href="{{ route('dashboard.ticket.show', $ticket->id) }}" class="btn btn-info"><i
                        class="fa fa-eye" aria-hidden="true"></i></a>
                    <a href="{{ route('dashboard.ticket.edit', $ticket->id) }}" class="btn btn-warning"><i
                        class="fa fa-pen" aria-hidden="true"></i></a>
                    <form action="{{ route('dashboard.ticket.destroy', $ticket->id) }}" method="POST" class="d-inline">
                      @csrf
                      @method('delete')
                      <button class="btn btn-danger btn-delete" data-toggle="tooltip" title='Delete'><i
                          class="fas fa-trash" aria-hidden="true"></i></button>
                    </form>
                  </td>
                </tr>
                @empty
                <tr>
                  <td colspan="6" class="text-center">Tidak ada data</td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-libraries')
<script src={{ asset("assets/module/datatables/media/js/jquery.dataTables.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-bs4/js/dataTables.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-select-bs4/js/select.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/sweetalert/dist/sweetalert.min.js") }}></script>
@endpush

@push('js-page')
<script src={{ asset("assets/js/page/modules-datatables.js") }}></script>
@endpush

@push('alert-js')
<script>
  $(".btn-delete").click(function(e) {
    var form = $(this).closest("form");
    var name = $(this).data("name");
    e.preventDefault();
    swal({
      title: 'Yakin ingin menghapus data?',
      text: 'Data akan masuk ke dalam menu trash',
      icon: 'warning',
      buttons: true,
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        form.submit();
      } else {
        swal('Proses Hapus dibatalkan');
      }
    });
  });
</script>
@endpush

resources/views/pages/dashboard/ticket/print.blade.php
@extends('layouts.app-print')

@section('content')
<div class="">
  <h3 class="text-center my-5">Laporan Data Tiket</h3>
  <table class="table table-bordered ">
    <thead class="thead-light">
      <tr class="text-center">
        <th>No</th>
        <th>Nama</th>
        <th>Pesawat</th>
        <th>Tanggal Pesan</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      @forelse ($tickets as $ticket)
      <tr class="text-center">
        <td>{{ $loop->iteration }}</td>
        <td>{{ $ticket->customer->nama ?? '' }}</td>
        <td>{{ $ticket->schedule->plane->nama ?? '' }}</td>
        <td>{{ $ticket->tanggal_pesan }}</td>
        <td>{{ $ticket->status }}</td>
      </tr>
      @empty
      <tr>
        <td colspan="5" class="text-center">Tidak ada data</td>
      </tr>
      @endforelse
    </tbody>
  </table>
</div>

@endsection

resources/views/pages/dashboard/ticket/show.blade.php
@extends('layouts.app')

@section('title')
Detail Tiket {{ $ticket->kode_tiket }}
@endsection

@section('content')
<div class="section-header">
  <h1>Detail Data ticket {{ $ticket->kode_tiket }}</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('dashboard.') }}">Dashboard</a></div>
    <div class="breadcrumb-item active"><a href="{{ route('dashboard.ticket.index') }}">Data Tiket</a></div>
    <div class="breadcrumb-item">Detail Data</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body d-flex justify-content-between">
          <a href="{{ route('dashboard.print_detail.ticket', $ticket->id) }}" class=" btn btn-dark"><i
              class="fas fa-file-pdf" aria-hidden="true"></i> Cetak PDF</a>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered">
              <tr>
                <th>Nama</th>
                <td>{{ $ticket->customer->nama ?? '' }}</td>
              </tr>
              <tr>
                <th>No KTP</th>
                <td>{{ $ticket->customer->no_ktp ?? '' }}</td>
              </tr>
              <tr>
                <th>No Telepon</th>
                <td>{{ $ticket->customer->no_telepon ?? '-' }}</td>
              </tr>
              <tr>
                <th>Pesawat</th>
                <td>{{ $ticket->schedule->plane->nama ?? '' }}</td>
              </tr>
              <tr>
                <th>Maskapai</th>
                <td>{{ $ticket->schedule->plane->airline->nama ?? '' }}</td>
              </tr>
              <tr>
                <th>Rute</th>
                <td>{{ $ticket->schedule->route->airportOrigin->name ?? '' }} - {{
                  $ticket->schedule->route->airportDestination->name ?? '' }} ({{ $ticket->schedule->route->kode_rute
                  ?? '' }})</td>
              </tr>
              <tr>
                <th>Jadwal Terbang</th>
                <td>{{ $ticket->schedule->waktu_berangkat ?? '' }} - {{ $ticket->schedule->waktu_tiba ?? '' }}</td>
              </tr>
              <tr>
                <th>Tanggal Pesan</th>
                <td>{{ $ticket->tanggal_pesan }}</td>
              </tr>
              <tr>
                <th>Status</th>
                <td>{{ $ticket->status }}</td>
              </tr>
            </table>
            <div class="text-center">
              {!! $qrcode !!}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pages/dashboard/ticket/trash.blade.php
@extends('layouts.app')

@section('title')
Trashed Tiket | {{ config('app.name') }}
@endsection

@push('css-libraries')
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-bs4/css/dataTables.bootstrap4.min.css") }}>
<link rel="stylesheet" href={{ asset("assets/module/datatables.net-select-bs4/css/select.bootstrap4.min.css") }}>
@endpush

@section('content')
<div class="section-header">
  <h1>Trashed Data Tiket</h1>
  <div class="section-header-breadcrumb">
    <div class="breadcrumb-item active"><a href="{{ route('dashboard.') }}">Dashboard</a></div>
    <div class="breadcrumb-item">Trashed Data Rute</div>
  </div>
</div>

<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-striped" id="table-1">
              <thead>
                <tr>
                  <th>No</th>
                  <th>Nama</th>
                  <th>Pesawat</th>
                  <th>Tanggal Pesan</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @forelse ($tickets as $ticket)
                <tr>
                  <td>{{ $loop->iteration }}</td>
                  <td>{{ $ticket->customer->nama ?? ''}}</td>
                  <td>{{ $ticket->schedule->plane->nama ?? '' }}</td>
                  <td>{{ $ticket->tanggal_pesan }}</td>
                  <td>{{ $ticket->status }}</td>
                  <td>
                    <a href="{{ route('dashboard.restore.ticket', $ticket->id) }}"
                      class="btn btn-success btn-restore"><i class="fa fa-trash-restore" aria-hidden="true"></i></a>
                    <a href="{{ route('dashboard.delete.ticket', $ticket->id) }}" class="btn btn-danger btn-delete"><i
                        class="fa fa-trash" aria-hidden="true"></i></a>
                  </td>
                </tr>
                @empty
                <tr>
                  <td colspan="6" class="text-center">Tidak ada data</td>
                </tr>
                @endforelse
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@push('js-libraries')
<script src={{ asset("assets/module/datatables/media/js/jquery.dataTables.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-bs4/js/dataTables.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/datatables.net-select-bs4/js/select.bootstrap4.min.js") }}></script>
<script src={{ asset("assets/module/sweetalert/dist/sweetalert.min.js") }}></script>
@endpush

@push('js-page')
<script src={{ asset("assets/js/page/modules-datatables.js") }}></script>
@endpush

@push('alert-js')
<script>
  $('.btn-restore').on('click', function (e) {
    e.preventDefault();
    const url = $(this).attr('href');
    swal({
      title: 'Are you sure?',
      text: 'Data akan kembali ke daftar tiket',
      icon: 'warning',
      buttons: ["Cancel", "Yes!"],
    }).then(function(value) {
      if (value) {
        window.location.href = url;
      }
    });
  });
  $('.btn-delete').on('click', function (e) {
    e.preventDefault();
    const url = $(this).attr('href');
    swal({
      title: 'Are you sure?',
      text: 'Data akan dihapus permanen',
      icon: 'warning',
      buttons: ["Cancel", "Yes!"],
    }).then(function(value) {
      if (value) {
        window.location.href = url;
      }
    });
  });
</script>
@endpush